language: python
virtualenv:
  system_site_packages: true
sudo: required
addons:
  apt:
    packages:
    - dpkg-dev
    - build-essential
    - python2.7-dev
    - libjpeg-dev
    - libtiff-dev
    - libsdl1.2-dev
    - libgstreamer-plugins-base0.10-dev
    - libnotify-dev
    - freeglut3
    - freeglut3-dev
    - libsm-dev
    - libgtk-3-dev
    - libwebkitgtk-3.0-dev
    - libgeos-dev
    - python-gi
    - python-gi-cairo
cache: pip
python:
- 2.7
install:
- dpkg -S libgio
- sudo rm /etc/apt/sources.list.d/mongodb*.list
- sudo add-apt-repository --yes ppa:inkscape.dev/stable
- sudo apt-get update
- sudo apt-get install inkscape python-gi
- pip install -U pip
- pip install --no-binary shapely -r requirements.txt
- pip install flake8
- pip install pyinstaller
before_script:
- flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
- flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
- make dist
notifications:
  on_success: change
  on_failure: change
deploy:
  provider: releases
  api_key:
    secure: pYORXHcn0hPcMIo6+brVE+wYce272H4COp1iXmPvBUz64MAX0Bdm5UX6cTAvzwNd9Hhi2nnWebaoS5AiPelbZgQoZJXsy4whrp7+ZrkQZkhGcqsSqXN6j5k5xdGeFX4k37T7eGkFyajTAdIWB3locHcikKN6N6PnyCPxGD/xuxiD1fJSVKGqBOptBYsqFtMddKy3aT0nmRG/2pMElq2Fcxozo+rR00j2/3npVoh2VTRt2L0S/DrX3zKT4vi2+AQ1MmKEAfF/YxCPybJGPe+wHz4egs0+PIJYb7pSZL8Ja81IS4v5cmmy/r2la815amyRyXwZXbJwBX8h9wPa7dwGStMvJdUidlqaXjKMsWba3QbD6YHOi0+UOFvWeubCDqXKhqxVAvZyCvXCx2WPlBfGWsJDHK/j2pU5Iul5Jz2Zsa3PLYA3UeGWVy081SZNuklNdccKGTokntFnR3pGM/jDN/JK7RkvuPM5qQqn3gludQnrdo/Kw0I77hAEDasgUyO8cweSfyqOXBN0dkbLjfBVRslRRRuC5fV9MIqFvLclaPfMlxsSTdDO4MGJRsF7VvFySBdh0xK7Rm+Vb9jYjCR3FV+b8TRsnY0eD2eFM+rmQt/OYdNIs6emVrTXCcAIzq4JoKZdFDIDDRsiztGSjIBB0+rSXmiUMtCiUo5GS/7zxGs=
  file:
    - '*.tar.gz'
  file_glob: true
  skip_cleanup: true
  on:
    all_branches: true
